parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     amex
    database_user:     root
    database_password: fer

    mailer_transport:  gmail
    mailer_host:       localhost
    mailer_user:       nicolasfagotti
    mailer_password:   

    locale:            es
    secret:            ThisTokenIsNotSoSecretChangeIt
