Amex\TriviaBundle\Entity\Type:
    type: entity
    table: type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        type:
            type: string
            length: 45
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
