amex_trivia_homepage:
  pattern:  /
  defaults: { _controller: AmexTriviaBundle:Default:index }
  
amex_trivia_login:
  pattern:  /login
  defaults: { _controller: AmexTriviaBundle:Security:login }
  
login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
  
amex_trivia_registro:
  pattern:  /registro
  defaults: { _controller: AmexTriviaBundle:Default:registro }
  
amex_trivia_ranking:
  pattern:  /ranking/{numberDia}/{dia}
  defaults: { _controller: AmexTriviaBundle:Default:ranking }

amex_trivia_recuperar_clave:
  pattern:  /recuperar-clave
  defaults: { _controller: AmexTriviaBundle:Default:recuperarClave }

amex_trivia_inicio:
  pattern: /inicio
  defaults: { _controller: AmexTriviaBundle:Default:inicio }
  
amex_trivia_trivia:
  pattern: /inicio/trivia
  defaults: { _controller: AmexTriviaBundle:Trivia:trivia }
  
amex_trivia_trivia_resultado:
  pattern: /inicio/trivia/{respuesta}
  defaults: { _controller: AmexTriviaBundle:Trivia:triviaCheck }

amex_trivia_verdadero_falso:
  pattern: /inicio/verdadero-falso
  defaults: { _controller: AmexTriviaBundle:Trivia:verdaderoFalso }
  
amex_trivia_verdadero_falso_resultado:
  pattern: /inicio/verdadero-falso/{respuesta}
  defaults: { _controller: AmexTriviaBundle:Trivia:verdaderoFalsoCheck }

amex_trivia_desafio:
  pattern: /inicio/desafio
  defaults: { _controller: AmexTriviaBundle:Trivia:desafio }
  
amex_trivia_desafio_resultado:
  pattern: /inicio/desafio/{uaId}
  defaults: { _controller: AmexTriviaBundle:Trivia:desafioCheck }
  
amex_email_bienvenida:
  pattern: /email/bienvenida
  defaults: { _controller: AmexTriviaBundle:Email:bienvenida }

amex_email_motivador:
  pattern: /email/motivador
  defaults: { _controller: AmexTriviaBundle:Email:motivador }

amex_email_ganador_dia:
  pattern: /email/ganador-dia
  defaults: { _controller: AmexTriviaBundle:Email:ganadorDia }

amex_email_ganador_final:
  pattern: /email/ganador-final
  defaults: { _controller: AmexTriviaBundle:Email:ganadorFinal }
  
amex_email_mecanica:
  pattern: /email/mecanica
  defaults: { _controller: AmexTriviaBundle:Email:mecanica }
  
